GymFitPlus.Web/Controllers/StatisticController.cs
using GymFitPlus.Core.Contracts;
using GymFitPlus.Core.ViewModels.StatisticViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using static GymFitPlus.Core.ErrorMessages.ErrorMessages;

namespace GymFitPlus.Web.Controllers
{
    public class StatisticController : BaseController
    {
        private readonly IStatisticService _statisticService;
        private readonly ILogger<StatisticController> _logger;

        public StatisticController(IStatisticService statisticService, ILogger<StatisticController> logger)
        {
            _statisticService = statisticService;
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var viewModel = new UserStatsViewModel();

            ViewBag.RegState = "ThirdStateOfRegister";

            return View(nameof(ChangeStats), viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> ChangeStats()
        {
            try
            {
                var viewModel = await _statisticService.GetUserLastAllStatsAsync(User.Id());

                return View(viewModel);
            }
            catch (NullReferenceException ex)
            {
                _logger.LogError("{Message:}", $"{NullReferenceErrorMessage} {ex.Message}");
                return View(new UserStatsViewModel());
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}", ex.Message);
                return BadRequest();
            }
        }

        [HttpPost]
        public async Task<IActionResult> ChangeStats(UserStatsViewModel viewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(viewModel);
                }

                viewModel.UserId = User.Id();
                viewModel.DateOfМeasurements = DateTime.Today;

                bool result = await _statisticService.UpdateUserStatsAsync(viewModel);

                if (result)
                {
                    TempData["UserMessageSuccess"] = "Successfully updated statistics";
                }
                else
                {
                    TempData["UserMessageError"] = "Аn error occurred, please try again later";
                }

                return RedirectToAction(nameof(AccountController.Dashboard), "Account");
            }
            catch (NullReferenceException ex)
            {
                _logger.LogError("{Message:}", $"{NullReferenceErrorMessage} {ex.Message}");
                return NotFound();
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}", ex.Message);
                return BadRequest();
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetStats(string statsType)
        {
            try
            {
                var viewModel = await _statisticService.GetUserConcreteStatsAsync(statsType, User.Id());

                return Json(viewModel);
            }
            catch (NullReferenceException ex)
            {
                _logger.LogError("{Message:}", $"{NullReferenceErrorMessage} {ex.Message}");
                return NotFound();
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}", ex.Message);
                return BadRequest();
            }
        }
    }
}

GymFitPlus.Web/Views/Statistic/ChangeStats.cshtml
@model UserStatsViewModel
@{
    ViewBag.Title = "Update Stats";
}

@section Styles {
    <link rel="stylesheet" href="~/css/AddExercise.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/ChangeStats.css" asp-append-version="true" />
}

<header class="text-center mb-5">
    <h1>Update Statistics</h1>
</header>
<hr/>

<div class="container">
    <div class="row text-center">
        <div class="row justify-content-center">
            <div class="col-sm-12 p-5 box">
                <form asp-area="" asp-action="ChangeStats" asp-controller="Statistic" method="post">

                    <div class="form-group">
                        <input asp-for="Weight" type="text" class="form-style" placeholder="Weight">
                        <i class="input-icon">Weight [kg]</i>
                        <span asp-validation-for="Weight" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-2">
                        <input asp-for="Height" type="text" class="form-style" placeholder="Height">
                        <i class="input-icon">Height [m]</i>
                        <span asp-validation-for="Height" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-2">
                        <input asp-for="ChestCircumference" type="text" class="form-style" placeholder="Chest Circumference">
                        <i class="input-icon">Chest [cm]</i>
                        <span asp-validation-for="ChestCircumference" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-2">
                        <input asp-for="BackCircumference" type="text" class="form-style" placeholder="Back Circumference">
                        <i class="input-icon">Back [cm]</i>
                        <span asp-validation-for="BackCircumference" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-2">
                        <input asp-for="RightArmCircumference" type="text" class="form-style" placeholder="Right Arm Circumference">
                        <i class="input-icon">Arm-R [cm]</i>
                        <span asp-validation-for="RightArmCircumference" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-2">
                        <input asp-for="LeftArmCircumference" type="text" class="form-style" placeholder="Left Arm Circumference">
                        <i class="input-icon">Arm-L [cm]</i>
                        <span asp-validation-for="LeftArmCircumference" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-2">
                        <input asp-for="WaistCircumference" type="text" class="form-style" placeholder="Waist Circumference">
                        <i class="input-icon">Waist [cm]</i>
                        <span asp-validation-for="WaistCircumference" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-2">
                        <input asp-for="GluteusCircumference" type="text" class="form-style" placeholder="Gluteus Circumference">
                        <i class="input-icon">Gluteus [cm]</i>
                        <span asp-validation-for="GluteusCircumference" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-2">
                        <input asp-for="RightLegCircumference" type="text" class="form-style" placeholder="Right Leg Circumference">
                        <i class="input-icon">Leg-R [cm]</i>
                        <span asp-validation-for="RightLegCircumference" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-2">
                        <input asp-for="LeftLegCircumference" type="text" class="form-style" placeholder="Left Leg Circumference">
                        <i class="input-icon">Leg-L [cm]</i>
                        <span asp-validation-for="LeftLegCircumference" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-2">
                        <input asp-for="RightCalfCircumference" type="text" class="form-style" placeholder="Right Calf Circumference">
                        <i class="input-icon">Calf-R [cm]</i>
                        <span asp-validation-for="RightCalfCircumference" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-2">
                        <input asp-for="LeftCalfCircumference" type="text" class="form-style" placeholder="Left Calf Circumference">
                        <i class="input-icon">Calf-L [cm]</i>
                        <span asp-validation-for="LeftCalfCircumference" class="text-danger"></span>
                    </div>

                    <button type="submit" class="btnn btn-block mt-5">Complete</button>

                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}