GymFitPlus.Web/Areas/Admin/Controllers/FitnessProgramController.cs
using GymFitPlus.Core.Contracts;
using GymFitPlus.Core.ViewModels.FitnessProgramViewModels;
using Microsoft.AspNetCore.Mvc;
using static GymFitPlus.Core.ErrorMessages.ErrorMessages;

namespace GymFitPlus.Web.Areas.Admin.Controllers
{
    public class FitnessProgramController : AdminBaseController
    {
        private readonly IFitnessProgramService _fitnessProgramService;
        private readonly ILogger<FitnessProgramController> _logger;

        public FitnessProgramController(IFitnessProgramService fitnessProgramService, ILogger<FitnessProgramController> logger)
        {
            _fitnessProgramService = fitnessProgramService;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Index(QueryFitnessProgramViewModel viewModel)
        {
            try
            {
                if (!string.IsNullOrEmpty(viewModel.Username))
                {
                    TempData["Username"] = viewModel.Username;

                    viewModel.UserDeletedFitnessPrograms = await _fitnessProgramService.GetUserAllDeletedFitnessProgramsAsync(viewModel.Username);
                }

                return View(viewModel);
            }
            catch (NullReferenceException ex)
            {
                _logger.LogError("{Message:}", $"{NullReferenceErrorMessage} {ex.Message}");
                return NotFound();
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}", ex.Message);
                return BadRequest();
            }         
        }

        [HttpPost]
        public async Task<IActionResult> RestoreFitnessProgram(int id)
        {
            try
            {
                bool result = await _fitnessProgramService.RestoreFitnessProgramAsync(id);

                if (result)
                {
                    TempData["UserMessageSuccess"] = "Successfully restored fitness program";
                }
                else
                {
                    TempData["UserMessageError"] = "Аn error occurred, please try again later";
                }

                return RedirectToAction(nameof(Index), new { username = TempData["Username"] });
            }
            catch (NullReferenceException ex)
            {
                _logger.LogError("{Message:}", $"{NullReferenceErrorMessage} {ex.Message}");
                return NotFound();
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}", ex.Message);
                return BadRequest();
            }
        }
    }
}

GymFitPlus.Web/Controllers/FitnessProgramController.cs
using GymFitPlus.Core.Contracts;
using GymFitPlus.Core.ViewModels.FitnessProgramViewModels;
using GymFitPlus.Core.ViewModels.WorkoutViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System.Security.Claims;
using static GymFitPlus.Core.ErrorMessages.ErrorMessages;

namespace GymFitPlus.Web.Controllers
{
    public class FitnessProgramController : BaseController
    {
        private readonly IFitnessProgramService _fitnessProgramService;
        private readonly ILogger<FitnessProgramController> _logger;

        public FitnessProgramController(
            IFitnessProgramService fitnessProgramService,
            ILogger<FitnessProgramController> logger)
        {
            _fitnessProgramService = fitnessProgramService;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Index(bool startWorkout = false)
        {
            try
            {
                IEnumerable<FitnessProgramFormViewModel> allPrograms = await _fitnessProgramService.AllFitnessProgramsAsync(User.Id());

                if (startWorkout)
                {
                    return View("StartWorkout", allPrograms);
                }

                return View(allPrograms);
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}", ex.Message);
                return BadRequest();
            }         
        }

        [HttpGet]
        public IActionResult AddProgram()
        {
            var model = new FitnessProgramFormViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddProgram(FitnessProgramFormViewModel viewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(viewModel);
                }

                bool result = await _fitnessProgramService.AddFitnessProgramAsync(viewModel, User.Id());

                if (result)
                {
                    TempData["UserMessageSuccess"] = $"Successfully was created fitness program {viewModel.Name}";
                }
                else
                {
                    TempData["UserMessageError"] = "Аn error occurred, please try again later";
                }

                return RedirectToAction(nameof(Index));
            }
            catch (NullReferenceException ex)
            {
                _logger.LogError("{Message:}", $"{NullReferenceErrorMessage} {ex.Message}");
                return NotFound();
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}", ex.Message);
                return BadRequest();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id, bool startWorkout = false)
        {
            try
            {
                var program = await _fitnessProgramService.FindFitnessProgramByIdAsync(id);

                TempData["FitnessProgramId"] = program.Id;

                if (startWorkout)
                {                   
                    if (TempData.Get<WorkoutDetailViewModel>("WorkoutModel") != null && TempData["WorkoutModelErrors"] != null)
                    {
                        if (TempData["WorkoutModelErrors"] is string[] errorsWorkout && errorsWorkout.Any())
                        {
                            foreach (var error in errorsWorkout)
                            {
                                ModelState.AddModelError("", error);
                            }
                        }

                        ViewBag.ValidationError = true;
                        ViewBag.WorkoutModel = TempData.Get<WorkoutDetailViewModel>("WorkoutModel");
                    }
                    else
                    {
                        ViewBag.WorkoutModel = new WorkoutDetailViewModel() { FitnessProgramId = program.Id };
                    }

                    return View("StartWorkoutDashboard", program);
                }

                if (TempData["NameErrors"] != null)
                {
                    if (TempData["NameErrors"] is Dictionary<string,string> errors && errors.Any())
                    {
                        foreach (var error in errors)
                        {
                            ModelState.AddModelError(error.Key, error.Value);
                        }
                    }                  
                }

                return View(program);
            }
            catch (NullReferenceException ex)
            {
                _logger.LogError("{Message:}", $"{NullReferenceErrorMessage} {ex.Message}");
                return NotFound();
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}", ex.Message);
                return BadRequest();
            }        
        }

        [HttpPost]
        public async Task<IActionResult> Delete(FitnessProgramDetailViewModel viewModel)
        {
            try
            {
                if ((int?)TempData["FitnessProgramId"] != viewModel.Id)
                {
                    _logger.LogError("{Message:}", TryToEditNotChoosenOne);
                    return BadRequest();
                }
                 
                bool result = await _fitnessProgramService.DeleteFitnessProgramAsync(viewModel.Id);

                if (result)
                {
                    TempData["UserMessageSuccess"] = $"Successfully deleted fitness program {viewModel.Name}";
                }
                else
                {
                    TempData["UserMessageError"] = "Аn error occurred, please try again later";
                }

                return RedirectToAction(nameof(Index));
            }
            catch (NullReferenceException ex)
            {
                _logger.LogError("{Message:}", $"{NullReferenceErrorMessage} {ex.Message}");
                return NotFound();
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}", ex.Message);
                return BadRequest();
            }
        }

        [HttpPost]
        public async Task<IActionResult> EditProgramName(FitnessProgramDetailViewModel viewModel)
        {
            try
            {
                if ((int?)TempData["FitnessProgramId"] != viewModel.Id)
                {
                    _logger.LogError("{Message:}", TryToEditNotChoosenOne);
                    return BadRequest();
                }

                if (ModelState.IsValid)
                {
                    bool result = await _fitnessProgramService.EditFitnessProgramAsync(viewModel);

                    if (result)
                    {
                        TempData["UserMessageSuccess"] = $"Successfully change name to {viewModel.Name}";
                    }
                    else
                    {
                        TempData["UserMessageError"] = "Аn error occurred, please try again later";
                    }
                }
                else
                {
                    Dictionary<string, string> errors = new();

                    foreach (var error in ModelState)
                    {
                        foreach (var item in error.Value.Errors)
                        {
                            errors.Add(error.Key, item.ErrorMessage);
                        }
                    }

                    TempData["ModalToShow"] = "ProgramNameModal";
                    TempData["NameErrors"] = errors;
                }

                return RedirectToAction("Details", new { id = viewModel.Id });
            }
            catch (NullReferenceException ex)
            {
                _logger.LogError("{Message:}", $"{NullReferenceErrorMessage} {ex.Message}");
                return NotFound();
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}", ex.Message);
                return BadRequest();
            }        
        }

        [HttpGet]
        public async Task<IActionResult> GetAllProgramsAjax(int withoutExerciseId)
        {
            try
            {
                var programs = await _fitnessProgramService.GetAllFitnessProgramsFilltered(User.Id(), withoutExerciseId);

                return Json(programs);
            }
            catch (NullReferenceException ex)
            {
                _logger.LogError("{Message:}", $"{NullReferenceErrorMessage} {ex.Message}");
                return NotFound();
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}", ex.Message);
                return BadRequest();
            }          
        }
    }
}

GymFitPlus.Web/Views/FitnessProgram/AddProgram.cshtml
@model FitnessProgramFormViewModel
@{
    ViewBag.Title = "Create program";
}
@section Styles {
    <link rel="stylesheet" href="~/css/AddExercise.css" asp-append-version="true" />
}

<div class="container-fluid mt-5">
    <div class="row justify-content-center">
        <div class="d-flex align-items-center justify-content-center mb-5">
            <h1>
                Here is a begining
            </h1>
        </div>
        <hr />
        <div class="col-md-6">
            <form asp-area="" asp-controller="FitnessProgram" asp-action="AddProgram" method="post" class="mt-5">
                <input asp-for="Id" hidden />             
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <input class="form-style" asp-for="Name" type="text" placeholder="Program Name"/>
                    <i class="input-icon material-symbols-light--exercise-outline"></i>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <input class="form-control btnn" type="submit" value="Create" />
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GymFitPlus.Web/Views/FitnessProgram/EditExerciseInProgram.cshtml
@model FitnessProgramExercisesInfoViewModel

@{
    ViewBag.Title = "Partial";
}

<form asp-controller="FitnessProgram" asp-action="EditExerciseInProgram" method="post">

    <input asp-for="FitnessProgramId" hidden>
    <input asp-for="ExerciseId" hidden>

    <div class="col-md-4">
        <label asp-for="Order" class="form-label"></label>
        <input asp-for="Order" type="text" class="form-control" required>
        <span asp-validation-for="Order" class="alert-danger"></span>
    </div>

    <div class="col-md-4">
        <label asp-for="Sets" class="form-label"></label>
        <input asp-for="Sets" type="text" class="form-control" required>
        <span asp-validation-for="Sets" class="alert-danger"></span>
    </div>

    <div class="col-md-4">
        <label asp-for="Reps" class="form-label"></label>
        <input asp-for="Reps" type="text" class="form-control" required>
        <span asp-validation-for="Reps" class="alert-danger"></span>
    </div>

    <div class="col-md-4">
        <label asp-for="Weight" class="form-label"></label>
        <input asp-for="Weight" type="text" class="form-control" required>
        <span asp-validation-for="Weight" class="alert-danger"></span>
    </div>

    <div class="col-12">
        <button class="btn btn-primary" type="submit">Submit form</button>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GymFitPlus.Web/Views/FitnessProgram/Index.cshtml
@model IEnumerable<FitnessProgramFormViewModel>
@{
    ViewBag.Title = "My programs";
}

@section Styles {
    <link rel="stylesheet" href="~/css/AddExercise.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StartWorkout.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/FitnessProgramIndex.css" asp-append-version="true" />
}

<header class="text-center">
    <h1>My Fitness Programs</h1>
</header>


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-3 center-div">
            <a class="btnn nav-link d-flex justify-content-center" asp-area="" asp-controller="FitnessProgram" asp-action="AddProgram">Create program</a>
        </div>
    </div>
</div>


<div class="container">
    <div class="row text-center">
        <div class="row justify-content-center">
            @foreach (var item in Model)
            {
                <div class="card col-md-2 box">
                    <a asp-area="" asp-controller="FitnessProgram" asp-action="Details" asp-route-id="@item.Id" class="btn linkbtn">
                        <div>
                            <div class="card-body text-light">
                                <h3 class="card-title">@item.Name</h3>
                                <p class="card-text"> Have @item.ExerciseCount exercise.</p>
                            </div>
                        </div>
                    </a>
                </div>
            }
        </div>
    </div>
</div>

GymFitPlus.Web/Views/FitnessProgram/StartWorkout.cshtml
@model IEnumerable<FitnessProgramFormViewModel>
@{
    ViewBag.Title = "Choose program";
}

@section Styles {
    <link rel="stylesheet" href="~/css/AddExercise.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StartWorkout.css" asp-append-version="true" />
}

<header class="text-center">
    <h1>Choose Fitness Program</h1>
</header>


<div class="container">
    <div class="row text-center">
        <div class="row justify-content-center">
            @foreach (var item in Model)
            {
                <div class="card col-md-2 box" style="border-radius: 50px;">
                    <a asp-area="" asp-controller="FitnessProgram" asp-action="Details" asp-route-id="@item.Id" asp-route-startWorkout="true" class="btn linkbtn">
                        <div>
                            <div class="card-body text-light">
                                <h3 class="card-title">@item.Name</h3>
                                <p class="card-text"> Have @item.ExerciseCount exercise.</p>
                            </div>
                        </div>
                    </a>
                </div>
            }
        </div>
    </div>
</div>

GymFitPlus.Web/Views/FitnessProgram/StartWorkoutDashboard.cshtml
@model FitnessProgramDetailViewModel
@{
    ViewBag.Title = Model.Name;
}

@section Styles {
    <link rel="stylesheet" href="~/css/AddExercise.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/IndexExercises.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StartWorkoutDashboard.css" asp-append-version="true" />
}

<header class="text-center">
    <h1>@Model.Name</h1>
</header>

<div class="container ">
    <div class="row justify-content-center">
        <div class="col-md-3 center-div mb-0" style="position:relative;">
            <div id="startDiv">
                <button class="btnn nav-link d-flex justify-content-center" id="startButton">Start Workout</button>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row justify-content-center ">
        <div class="col-md-3 center-div mb-5 pb-5" style="position:relative;">
            <div class="d-flex justify-content-center" id="divTimer">
                <p id="timer"></p>
            </div>
        </div>
    </div>
</div>
<hr />
<div class="progress mt-3 mb-3" role="progressbar" aria-valuemin="0" aria-valuemax="100">
    <div class="progress-bar custom-progress-bar" id="progress-bar" style="width:0%">50%</div>
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-12">
            <div class="table">
                <table class="table text-light" id="myTable">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Exercise</th>
                            <th scope="col" class="text-center">Sets</th>
                            <th scope="col" class="text-center">Reps</th>
                            <th scope="col" class="text-center">Weight</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Exercises.OrderBy(x => x.Order))
                        {
                            string uniqueID = $"element{item.FitnessProgramId}{item.ExerciseId}edit";

                            <tr>
                                <th scope="row">@item.Order</th>
                                <td>
                                    @item.ExerciseName
                                    <label class="toggle" for="@uniqueID" style="visibility:hidden;">
                                        <input type="checkbox" class="toggle__input checkbox" id="@uniqueID" />
                                        <span class="toggle-track">
                                            <span class="toggle-indicator">
                                                <span class="checkMark">
                                                    <svg viewBox="0 0 24 24" id="ghq-svg-check" role="presentation" aria-hidden="true">
                                                        <path d="M9.86 18a1 1 0 01-.73-.32l-4.86-5.17a1.001 1.001 0 011.46-1.37l4.12 4.39 8.41-9.2a1 1 0 111.48 1.34l-9.14 10a1 1 0 01-.73.33h-.01z"></path>
                                                    </svg>
                                                </span>
                                            </span>
                                        </span>
                                    </label>
                                </td>
                                <td class="text-center setsCol">@item.Sets</td>
                                <td class="text-center">@item.Reps</td>
                                <td class="text-center">@item.Weight</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div id="finishForm">
    @await Component.InvokeAsync("WorkoutFormDataComponent", new { viewModel = ViewBag.WorkoutModel })
</div>

<div class="row mb-5">
    <div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-start">
        <button id="upButton">
            <img src="~/images/pagination/UpArrow.svg" />
        </button>

    </div>

    <div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-end">
        <button id="downButton">
            <img src="~/images/pagination/DownArrow.svg" />
        </button>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/StartWorkoutDashboard.js"></script>
    @if (ViewBag.ValidationError != null && ViewBag.ValidationError)
    {
        <script>
            var timerInput = document.getElementById('timerInput');
            displayValidation(timerInput.value);
        </script>
    }
}