GymFitPlus.Web/Controllers/ExerciseController.cs
using GymFitPlus.Core.Contracts;
using GymFitPlus.Core.ViewModels.ExerciseViewModels;
using GymFitPlus.Core.ViewModels.FitnessProgramViewModels;
using Microsoft.AspNetCore.Mvc;
using static GymFitPlus.Core.ErrorMessages.ErrorMessages;

namespace GymFitPlus.Web.Controllers
{
    public class ExerciseController : BaseController
    {
        private readonly IExerciseService _exerciseService;
        private readonly ILogger<ExerciseController> _logger;

        public ExerciseController(IExerciseService exerciseService, ILogger<ExerciseController> logger)
        {
            _exerciseService = exerciseService;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] AllExercisesQueryModel query)
        {
            try
            {
                IEnumerable<ExerciseAllViewModel> model = await _exerciseService.AllExerciseAsync(query);

                ViewBag.Query = query;

                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}", ex.Message);
                return BadRequest();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                ExerciseDetailViewModel model = await _exerciseService.FindExerciseByIdAsync(id);

                return View(model);
            }
            catch (NullReferenceException ex)
            {
                _logger.LogError("{Message:}", $"{NullReferenceErrorMessage} {ex.Message}");
                return NotFound();
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}",ex.Message);
                return BadRequest();
            }
        }
     
        [HttpGet]
        public async Task<IActionResult> AddExerciseToProgram(int programId, int exerciseCount, int exerciseId = -1)
        {
            try
            {
                var model = new FitnessProgramExercisesInfoViewModel
                {
                    FitnessProgramId = programId,
                    ExerciseId = exerciseId,
                    Order = ++exerciseCount,
                    Exercises = await _exerciseService.GetAllExerciseForProgramAsync(programId)
                };

                return View(model);
            }
            catch (NullReferenceException ex)
            {
                _logger.LogError("{Message:}", $"{NullReferenceErrorMessage} {ex.Message}");
                return NotFound();
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}", ex.Message);
                return BadRequest();
            }        
        }

        [HttpPost]
        public async Task<IActionResult> AddExerciseToProgram(FitnessProgramExercisesInfoViewModel viewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    viewModel.Exercises = await _exerciseService.GetAllExerciseForProgramAsync(viewModel.FitnessProgramId);
                    return View(viewModel);
                }

                bool result = await _exerciseService.AddExerciseToProgramAsync(viewModel);

                if (result)
                {
                    TempData["UserMessageSuccess"] = "Successfully added exercise to program";
                }
                else
                {
                    TempData["UserMessageError"] = "Аn error occurred, please try again later";
                }

                return RedirectToAction(nameof(FitnessProgramController.Details),
                                        "FitnessProgram",
                                        new { id = viewModel.FitnessProgramId });
            }
            catch (NullReferenceException ex)
            {
                _logger.LogError("{Message:}", $"{NullReferenceErrorMessage} {ex.Message}");
                return NotFound();
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}", ex.Message);
                return BadRequest();
            }
        }

        [HttpPost]
        public async Task<IActionResult> EditExerciseFromProgram(FitnessProgramExercisesInfoViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool result = await _exerciseService.EditExerciseFromProgramAsync(viewModel);

                    if (result)
                    {
                        TempData["UserMessageSuccess"] = $"Successfully edited exercise {viewModel.ExerciseName}";
                    }
                    else
                    {
                        TempData["UserMessageError"] = "Аn error occurred, please try again later";
                    }
                }
                else
                {
                    Dictionary<string, string> errors = new();

                    foreach (var error in ModelState)
                    {
                        foreach (var item in error.Value.Errors)
                        {
                            errors.Add(error.Key, item.ErrorMessage);
                        }
                    }
                    TempData["ModalToShow"] = $"element{viewModel.FitnessProgramId}{viewModel.ExerciseId}edit";
                    TempData["FitnessProgramExerciseViewModelErrors"] = errors;
                }

                return RedirectToAction(nameof(FitnessProgramController.Details),
                                       "FitnessProgram",
                                       new { id = viewModel.FitnessProgramId });
            }
            catch (NullReferenceException ex)
            {
                _logger.LogError("{Message:}", $"{NullReferenceErrorMessage} {ex.Message}");
                return NotFound();
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}", ex.Message);
                return BadRequest();
            }           
        }

        [HttpPost]
        public async Task<IActionResult> RemoveExerciseFromProgram(int exerciseId, int programId)
        {
            try
            {
                bool result = await _exerciseService.RemoveExerciseFromProgramAsync(exerciseId, programId);

                if (result)
                {
                    TempData["UserMessageSuccess"] = "Successfully deleted exercise";
                }
                else
                {
                    TempData["UserMessageError"] = "Аn error occurred, please try again later";
                }

                return RedirectToAction(nameof(FitnessProgramController.Details),
                                       "FitnessProgram",
                                       new { id = programId });
            }
            catch (NullReferenceException ex)
            {
                _logger.LogError("{Message:}", $"{NullReferenceErrorMessage} {ex.Message}");
                return NotFound();
            }
            catch (Exception ex)
            {
                _logger.LogError("{Message:}", ex.Message);
                return BadRequest();
            }            
        }
    }
}

GymFitPlus.Web/Views/Shared/Components/SearchExerciseComponent/Default.cshtml
@model AllExercisesQueryModel

<form asp-area="" asp-controller="Exercise" asp-action="Index" method="get">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-3 form-group">
                <input asp-for="SearchTerm" class="form-style" placeholder="Search">
                <i class="input-icon material-symbols--search"></i>
            </div>
            <div class="col-md-3 form-group">
                <select asp-for="Category" class="form-style" style="color: #ffeba7" aria-required="true">
                    <option disabled selected value="" style="color: #ffffff">Muscle group</option>
                    @foreach (var muscleGroup in Enum.GetValues(typeof(MuscleGroup)))
                    {
                        <option style="color: #ffffff" value="@muscleGroup">@muscleGroup</option>
                    }
                </select>
                <i class="input-icon ion--body-outline"></i>
            </div>
            <div class="col-md-3 form-group">
                <select asp-for="Sorting" class="form-style" style="color: #ffeba7" aria-required="true">
                    <option disabled selected value="" style="color: #ffffff">Sorting</option>
                    @foreach (var sorting in Enum.GetValues(typeof(Sorting)))
                    {
                        if ((Sorting)sorting == Sorting.Аlphabetical || (Sorting)sorting == Sorting.Interactions)
                        {
                            <option style="color: #ffffff" value="@sorting">@sorting</option>
                        }
                    }
                </select>
                <i class="input-icon icons8--alphabetical-sorting"></i>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-3 center-div mb-4">
                <input type="submit" value="Search Exercises" class="btnn search-btnn nav-link d-flex justify-content-center" />
            </div>
        </div>
    </div>
</form>

@{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalExerciseCount /
        Model.ExercisePerPage);

    var shouldButtonBeDisabled = Model.CurrentPage == maxPage;
}

<div class="nextPreviousBtn">
    <div class="leftPrevious">
        <div id="targetElementP" class="@(Model.CurrentPage == 1 ? "invisible" : string.Empty)">
            <a class="btn p-0 @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
               asp-area=""
               asp-controller="Exercise"
               asp-action="Index"
               asp-route-currentPage="@previousPage"
               asp-route-category="@Model.Category"
               asp-route-searchTerm="@Model.SearchTerm"
               asp-route-sorting="@((int)Model.Sorting)">
                <img id="targetImgP" src="/images/Pagination/PreviousArrow.svg" />
            </a>
        </div>
    </div>
    <div class="rightNext">
        <div id="targetElementN" class="@(shouldButtonBeDisabled ? " invisible" : string.Empty)">
            <a class="btn p-0 @(shouldButtonBeDisabled ? " disabled" : string.Empty)"
               asp-area=""
               asp-controller="Exercise"
               asp-action="Index"
               asp-route-currentPage="@(Model.CurrentPage + 1)"
               asp-route-category="@Model.Category"
               asp-route-searchTerm="@Model.SearchTerm"
               asp-route-sorting="@((int)Model.Sorting)">
                <img id="targetImgN" src="/images/Pagination/NextArrow.svg" />
            </a>
        </div>
    </div>
</div>